# Generated by Django 5.1 on 2024-11-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.departamento')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.rol')),
            ],
        ),
    ]
