# Generated by Django 5.1 on 2024-12-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_casos_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Abierto'), (2, 'En proceso'), (3, 'Cerrado')], default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Muy Alto')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
