# Generated by Django 5.1 on 2024-12-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_estado_ticket_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipoCaso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.casos'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.usuario'),
        ),
    ]
