# Generated by Django 5.1 on 2024-12-04 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_categoria_ticket_admin_asignado_ticket_resolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='admin_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_asignado', to='tickets.usuario'),
        ),
    ]
