# Generated by Django 5.1 on 2024-12-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_admin_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.categoria'),
        ),
    ]
