# Generated by Django 5.1 on 2024-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_comentario_fecha_creacion_alter_comentario_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='example@altamiragroup.com.py', max_length=50),
        ),
    ]
