# Generated by Django 5.1 on 2024-12-05 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='example@altamiragroup.com.py', max_length=50, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.')]),
        ),
    ]
