# Generated by Django 5.1 on 2024-12-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Abierto'), (2, 'En proceso'), (3, 'En espera de feedback'), (4, 'Cerrado')], default=1),
        ),
    ]
