# Generated by Django 5.1 on 2024-12-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
