# Generated by Django 5.1 on 2024-12-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_casos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.categoria'),
        ),
    ]
