# Generated by Django 5.1 on 2025-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_casos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tiempo_resolucion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
