# Generated by Django 5.1 on 2025-01-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_tiempo_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cambiar_contrasena',
            field=models.BooleanField(default=False),
        ),
    ]
