# Generated by Django 5.1 on 2025-01-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_usuario_cambiar_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cambiar_contrasena',
        ),
        migrations.AddField(
            model_name='usuario',
            name='necesita_cambiar_contrasena',
            field=models.BooleanField(default=False),
        ),
    ]
