# Generated by Django 5.1 on 2025-01-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_remove_usuario_cambiar_contrasena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='necesita_cambiar_contrasena',
        ),
    ]
