# Generated by Django 5.1 on 2025-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_alter_usuario_necesita_cambiar_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='necesita_cambiar_contrasena',
            field=models.BooleanField(default=False),
        ),
    ]
