# Generated by Django 5.1 on 2025-01-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_usuario_necesita_cambiar_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
    ]
