# Generated by Django 5.1 on 2025-01-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='horario_asignacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
