# Generated by Django 5.1 on 2025-01-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_ticket_horario_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='horario_asignacion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tiempo_resolucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
