# Generated by Django 5.1 on 2025-01-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_ticket_horario_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tiempo_resolucion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
