# Generated by Django 5.1 on 2025-01-30 08:13

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_alter_ticket_tiempo_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=tickets.models.ticket_upload_path),
        ),
    ]
