# Generated by Django 5.2.8 on 2025-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_tokenrestablecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
