# Generated by Django 5.2.8 on 2025-12-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_ticket_fecha_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Fecha_duracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
