# Generated by Django 5.2.8 on 2025-12-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_ticket_fecha_duracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Fecha_duracion',
            new_name='fecha_hora_resolucion',
        ),
    ]
