# Generated by Django 5.2.8 on 2025-12-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_rename_fecha_duracion_ticket_fecha_hora_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to='tickets.usuario'),
        ),
    ]
