# Generated by Django 5.2.8 on 2025-12-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_ticket_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tiempo_fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
