# Generated by Django 5.2.8 on 2025-12-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_ticket_tiempo_fecha_resolucion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tiempo_fecha_resolucion',
            new_name='tiempo_fecha_asignacion',
        ),
    ]
