# Generated by Django 5.1.7 on 2026-05-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_rename_tiempo_fecha_resolucion_ticket_tiempo_fecha_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionCampoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opción de Campo Administrativo',
                'verbose_name_plural': 'Opciones de Campo Administrativo',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='campo_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.opcioncampoadmin', verbose_name='Campo Administrativo'),
        ),
    ]
